In [1]:
import random
import numpy as np
from cs231n.data_utils import load_CIFAR10
import matplotlib.pyplot as plt

In [14]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([1, 0, 2])

In [17]:
#arr1[:, y] = 3
print(arr1[:, y])

[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [18]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.sum(arr1, axis=0)

array([12, 15, 18])

In [27]:
arr1*mask

array([[0, 0, 0],
       [0, 5, 6],
       [7, 8, 9]])

In [54]:
a = np.array([[1,0], [2,0], [3,0], [4,0], [5,0], [6,0], [7,0], [8,0], [9,0]])
ai = np.array([0, 5, 8])
ai

array([0, 5, 8])

In [58]:
np.max(a, axis=1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(str(5e-2))

0.05
